### ISSUE TITLE
cdn version vs bower install version?

### ISSUE THREAD

**Issue by scheung38** [b-pos465/plotly_bower#1]
$ npm install --save bower -> 1.16.2

in myPlotly.js

```
import Plotly from '../../../bower_components/plotlyjs/plotly';
```

$ npm install

WARNING in ./bower_components/plotlyjs/plotly.js
Critical dependencies:
7:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./bower_components/plotlyjs/plotly.js 7:479-486

but if using CDN inside my index.html:

```
<head>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

```

then this gives version v1.17.3 and no warning as above...? So how to update bower instead of using cdn?

**Comment by b-pos465** [comment]
I updated the version to 1.18.1. This should fix it.
